services:
  messages-service:
    build: ../
    ports:
      - "8081:8080"
    depends_on:
      - pg-master
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: unless-stopped

  pg-master:
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  zabbix-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
    volumes:
      - zabbix_db_data:/var/lib/postgresql/data

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-7.0-latest
    ports:
      - "10051:10051"
    environment:
      DB_SERVER_HOST: zabbix-db
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
    depends_on:
      - zabbix-db

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-7.0-latest
    ports:
      - "8080:8080"
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: zabbix-db
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
    depends_on:
      - zabbix-server

  zabbix-agent:
    image: zabbix/zabbix-agent2:ubuntu-7.0-latest
    privileged: true
    user: root
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host:ro
    environment:
      - ZBX_HOSTNAME=DockerHost
      - ZBX_SERVER_HOST=127.0.0.1,172.20.0.5
    depends_on:
      - zabbix-server

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
      - zabbix-server

volumes:
  zabbix_db_data:
  prometheus_data:
  grafana_data:
