debezium.sink.type=kafka
debezium.sink.kafka.producer.bootstrap.servers=kafka:9092
debezium.sink.kafka.producer.key.serializer=org.apache.kafka.common.serialization.StringSerializer
debezium.sink.kafka.producer.value.serializer=org.apache.kafka.common.serialization.StringSerializer

debezium.source.key.converter=org.apache.kafka.connect.storage.StringConverter
debezium.source.key.converter.schemas.enable=false
debezium.source.value.converter=org.apache.kafka.connect.json.JsonConverter
debezium.source.value.converter.schemas.enable=false

debezium.source.transforms=unwrap,extractkey
debezium.source.transforms.unwrap.type=io.debezium.transforms.ExtractNewRecordState
debezium.source.transforms.extractkey.type=org.apache.kafka.connect.transforms.ExtractField$Key
debezium.source.transforms.extractkey.field=message_key

debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.source.offset.storage.file.filename=/debezium/data/offsets.dat
debezium.source.database.hostname=pg-master
debezium.source.database.port=5432
debezium.source.database.user=postgres
debezium.source.database.password=password
debezium.source.database.dbname=mydb
debezium.source.topic.prefix=my_server
debezium.source.table.include.list=public.outbox_events
debezium.source.plugin.name=pgoutput
debezium.source.message.key.columns=public.outbox_events:message_key


