spring:
  datasource:
    master:
      url: jdbc:postgresql://localhost:5432/mydb
    slave:
      url: jdbc:postgresql://localhost:5433/mydb
logging:
  level:
    ru:
      otus:
        highload:
          sn: DEBUG
